# Generated by Django 5.1.4 on 2024-12-31 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='realtors/%Y/%M/%d')),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('is_mvp', models.BooleanField(default=False)),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('lot_size', models.FloatField()),
                ('list_date', models.DateTimeField(auto_now_add=True)),
                ('photo_main', models.CharField(max_length=255)),
                ('photo_1', models.ImageField(upload_to='listings/%Y/%M/%d')),
                ('photo_2', models.CharField(max_length=255)),
                ('photo_3', models.CharField(max_length=255)),
                ('photo_4', models.CharField(max_length=255)),
                ('photo_5', models.CharField(max_length=255)),
                ('photo_6', models.CharField(max_length=255)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.realtor')),
            ],
        ),
    ]
