# Generated by Django 5.1.4 on 2024-12-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(upload_to='listings/%Y/%M/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(upload_to='listings/%Y/%M/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(upload_to='listings/%Y/%M/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(upload_to='listings/%Y/%M/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(upload_to='listings/%Y/%M/%d'),
        ),
    ]
